name: Deploy to Staging
on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy via SFTP
             uses: SamKirkland/SFTP-Deploy-Action@v6
             with:
                 server: ${{ secrets.SFTP_SERVER }}
                 username: ${{ secrets.SFTP_USERNAME }}
                 password: ${{ secrets.SFTP_PASSWORD }}
                 local-dir: ./wp-content/themes/magnum-capital/
                 server-dir: ${{secrets.SFTP_SERVER_DIR}}

           