name: Deploy to Staging
on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: 📂 Sync Files
              uses: SamKirkland/web-deploy@v1
              with:
                source-path: ./
                target-server: staging.magnumcapital.co.uk
                remote-user: id_rsa@staging.magnumcapital.co.uk
                private-ssh-key: ${{ secrets.SSH_KEY }}
                destination-path: ~/home/lukemers/staging.magnumcapital.co.uk/id_rsa